language: node_js
node_js:
  - '0.12'

env:
  global:
    secure: "cDWZIQ1y2JeQD199rgXvWD/lR3d1dznMhun72De2LaFOS6aF9Ah07bNDgGYKEaawQuW7OfIJu4nEa0TSqGdOsPceUQD6fLwcGKQg6MnkL7E6hvaBEWeK4QSqUn9/Fhon0SoDQOiK7DVwJ8/E7A76IH9yZ95lC4Q4ZIjiFPvLNLxB4eXQGRYYVNKfXk/a1oTJtqUY/NxsY8H4VSZ4sBYX+V4myxaDubLNqqscrA7NxBh4E2lGbW3UgAxD3uzsAZ7FuE1/1wET48DzqOzgMfQpqz+AJ5GGHFmjZQe2k+y7AyCA8qYbaCARH5XoXbWw81VvUhOLvgWUlMBebdxSa9rKmxnyifmOgczUtJXIwzDlPCylXBFoHSZicSfpe0XWfW3s06jNG9vEnq6IFcrqH/1504aV2O50nzWp5Safh1Dvcjh6SQ0JB6ggeS7Ros4R19ihTqdLl2OIOSaNtcYidc1Xsfeu7pstEYmL9KUbI2hu/uc2p4vANpk6xxUa7XFRFFqMxtHKxZZeGfGxOY4lVeJKh00SgRTJsaglDs8u3qJny1dd5ERrfoMoQsefv9u4UCrgyWN8AaFDJw3RqX3RfBjFyYY0gonn/Wfknv0dFJOdxjdc6zLs3CfozqbekfCDA62Pq/vgviEj3tKoRNag/XTEl+3WQdlGUs4LhxpAwHRg1v0="

before_install:
  - npm install -g grunt-cli

script:
  - npm test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && grunt autoDeploy
